using UnityEngine;

public class ReplayMoveTurnButton : MonoBehaviour
{
	[SerializeField]
	public UIButton BackButton;

	[SerializeField]
	public UIButton MenuButton;

	[SerializeField]
	public UIButton ForwardButton;

	[SerializeField]
	public UIButton StopReplayButton;

	[SerializeField]
	public UIButton ForwardReplayButton;

	private void Awake()
	{
		EventDelegate.Set(BackButton.onClick, OnClickButton);
		EventDelegate.Set(MenuButton.onClick, OnClickButton);
		EventDelegate.Set(ForwardButton.onClick, OnClickButton);
	}

	private void OnClickButton()
	{
		GameMgr.GetIns().GetSoundMgr().PlaySe(Se.TYPE.SYS_BTN_DECIDE);
	}
}
