using UnityEngine;

namespace Wizard;

public class EmoteUI : MonoBehaviour
{
	[SerializeField]
	public NguiObjs[] EmoteBtnList;

	[SerializeField]
	public NguiObjs EmoteTextP;

	[SerializeField]
	public NguiObjs EmoteTextE;

	[SerializeField]
	public NguiObjs ThinkTextE;

	public float EmoteDelayTime;

	public bool isEmoteBtnEnabled = true;

	private void Update()
	{
		if (!isEmoteBtnEnabled)
		{
			emoteCheck();
		}
	}

	private void emoteCheck()
	{
		bool flag = true;
		if (EmoteDelayTime > 0f)
		{
			EmoteDelayTime -= Time.deltaTime;
			flag = false;
		}
		if (flag)
		{
			onEmotes();
		}
	}

	private void onEmotes()
	{
		isEmoteBtnEnabled = true;
		for (int i = 0; i < EmoteBtnList.Length; i++)
		{
			EmoteBtnList[i].buttons[0].enabled = true;
			EmoteBtnList[i].buttons[0].GetComponent<UISprite>().color = new Color(1f, 1f, 1f, 1f);
		}
	}
}
