using UnityEngine;

namespace Wizard;

public class ClassIconName : MonoBehaviour
{
	[SerializeField]
	private UILabel _labelClassName;

	[SerializeField]
	private UISprite _spriteClassIcon;

	public void SetClass(int classId)
	{
		ClassCharacterMasterData charaPrmByClassId = GameMgr.GetIns().GetDataMgr().GetCharaPrmByClassId(classId);
		_labelClassName.text = charaPrmByClassId._className;
		ClassCharaPrm.SetClassLabelSetting(_labelClassName, charaPrmByClassId.clan);
		_spriteClassIcon.spriteName = ClassCharaPrm.GetIconSpriteName(charaPrmByClassId.clan);
	}
}
