using UnityEngine;

namespace Wizard.Lottery;

public class LotterySpecialRewardDialog : MonoBehaviour
{
	[SerializeField]
	private UILabel _labelDescription;

	private LotteryRewardData _lotteryRewardData;

	public void Init(LotteryRewardData lotteryRewardData)
	{
		_lotteryRewardData = lotteryRewardData;
		_labelDescription.text = _lotteryRewardData.Description;
	}

	public void OnClickSpecialRewardSiteBtn()
	{
		GameMgr.GetIns().GetSoundMgr().PlaySe(Se.TYPE.SYS_BTN_DECIDE);
		if (_lotteryRewardData.IsSpecial)
		{
			UIManager.GetInstance().WebViewHelper.OpenUrl(_lotteryRewardData.LotteryUrl);
		}
	}
}
